import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../dist/", import.meta.url);

test("builds a GitHub Pages-ready field guide", async () => {
  const html = await readFile(new URL("index.html", root), "utf8");
  assert.match(html, /TT•SIM Lab/);
  assert.match(html, /og\.png/);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape/);
  await access(new URL("og.png", root));
  await access(new URL("TTSIM_DEBUGGING_PATH.md", root));
  await access(new URL("WSL_AGENT_HOST_DEVICE_DEBUGGING.md", root));
  await access(new URL("BLACKHOLE_SMOKE_TEST.md", root));
  await access(new URL("SIMULATION_SEQUENCE.md", root));
  await access(new URL("QUASAR_CLUSTER_LAB.md", root));
  await access(new URL("COMPILER_RUNTIME_CAPSTONE.md", root));
  await access(new URL("TENSTORRENT_GENERATION_COMPARISON.md", root));
  await access(new URL("BLACKHOLE_VS_HUAWEI_ASCEND.md", root));
  await access(new URL("ASYNC_KERNELS_AND_MATRIX_GRANULARITY.md", root));
  await access(new URL("CONTRIBUTION_ROADMAP.md", root));
  await access(new URL("DISCUSSION.md", root));
  await access(new URL("RISC_FIRMWARE_TO_KERNEL_FLOW.md", root));
  await access(new URL("huawei.html", root));
  await access(new URL("async-kernels.html", root));
  await access(new URL("firmware-flow.html", root));
  await access(new URL("discussion.html", root));
  await access(new URL("discussion-blackhole-bringup.html", root));
  await access(new URL("DISCUSSION_BLACKHOLE_BRINGUP.md", root));
  await access(new URL("discussion-blackhole-synchronization.html", root));
  await access(new URL("DISCUSSION_BLACKHOLE_SYNCHRONIZATION.md", root));
  await access(new URL("discussion-transformer-blackhole-optimization.html", root));
  await access(new URL("DISCUSSION_TRANSFORMER_BLACKHOLE_OPTIMIZATION.md", root));
  await access(new URL("discussion-presentation.html", root));
  await access(new URL("DISCUSSION_PRESENTATION_30_MIN.md", root));
  await access(new URL("discussion-quantization.html", root));
  await access(new URL("DISCUSSION_TT_METAL_QUANTIZATION.md", root));
  await access(new URL("debug-low-level-kernel-flow.html", root));
  await access(new URL("DEBUG_LOW_LEVEL_KERNEL_FLOW.md", root));
  await access(new URL("discussion-architecture-interview.html", root));
  await access(new URL("DISCUSSION_ARCHITECTURE_INTERVIEW.md", root));
});

test("publishes the low-level kernel Mermaid debug flow", async () => {
  const html = await readFile(new URL("debug-low-level-kernel-flow.html", root), "utf8");
  const main = await readFile(new URL("../src/debug-low-level-kernel-flow-main.tsx", root), "utf8");
  const packageJson = await readFile(new URL("../package.json", root), "utf8");
  const app = await readFile(new URL("../src/DebugLowLevelKernelFlowApp.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/debug-low-level-kernel-flow.css", root), "utf8");
  const guide = await readFile(new URL("../docs/DEBUG_LOW_LEVEL_KERNEL_FLOW.md", root), "utf8");
  const publishedGuide = await readFile(new URL("DEBUG_LOW_LEVEL_KERNEL_FLOW.md", root), "utf8");
  assert.match(html, /Low-level kernel debug flow/);
  assert.match(main, /from "mermaid"/);
  assert.match(main, /await mermaid\.run/);
  assert.match(packageJson, /"mermaid": "11\.17\.0"/);
  assert.match(app, /HOST → FIRMWARE → WRAPPER → KERNEL_MAIN → DONE/);
  assert.match(app, /R WITHOUT K/);
  assert.match(app, /K WITHOUT KD/);
  assert.match(app, /className="mermaid"/);
  assert.match(styles, /\.mermaid-shell/);
  const diagrams = [...guide.matchAll(/```mermaid\r?\n([\s\S]*?)```/g)].map((match) => match[1]);
  assert.ok(diagrams.length >= 6);
  assert.ok(diagrams.every((diagram) => /^(sequenceDiagram|flowchart TD)/.test(diagram)));
  assert.match(guide, /NCRISC does not call BRISC/);
  assert.match(guide, /dprint_server\.cpp/);
  assert.equal(publishedGuide, guide);
});

test("publishes the NPU architecture interview workbench", async () => {
  const html = await readFile(new URL("discussion-architecture-interview.html", root), "utf8");
  const main = await readFile(new URL("../src/architecture-interview-main.tsx", root), "utf8");
  const app = await readFile(new URL("../src/ArchitectureInterviewApp.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/architecture-interview.css", root), "utf8");
  const guide = await readFile(new URL("../docs/DISCUSSION_ARCHITECTURE_INTERVIEW.md", root), "utf8");
  const publishedGuide = await readFile(new URL("DISCUSSION_ARCHITECTURE_INTERVIEW.md", root), "utf8");
  assert.match(html, /NPU architecture interview workbench/);
  assert.match(main, /from "mermaid"/);
  assert.match(main, /await mermaid\.run/);
  assert.match(app, /Use BETRV/);
  assert.match(app, /THIRTEEN-TOPIC PLAN/);
  assert.match(app, /SEVENTEEN RECALL PROMPTS/);
  assert.match(app, /Tenstorrent experience boundary/);
  assert.match(app, /Huawei CANN \+ MindSpore/);
  assert.match(app, /BuiCongNguyen_ResumeEN_202607\.pdf/);
  assert.equal((app.match(/id: "(?:memory|transformer|quantization|compiler|fusion|scheduling|tenstorrent|huawei|performance|projects|questions|simulator|focus)"/g) ?? []).length, 13);
  const promptBlock = app.match(/const principalPrompts = \[([\s\S]*?)\] as const;/)?.[1] ?? "";
  assert.equal((promptBlock.match(/^  \["/gm) ?? []).length, 17);
  assert.match(app, /P ≤ min/);
  assert.match(app, /7B → 70B/);
  assert.match(app, /FP8 ≠ BFLOAT8_B/);
  assert.match(app, /Lower watts ≠ lower energy/);
  assert.match(styles, /\.scenario-tabs/);
  assert.match(styles, /\.option-table/);
  assert.match(styles, /\.prep-grid/);
  assert.match(styles, /\.question-grid/);
  assert.match(guide, /## 0\. Thirteen-topic preparation plan/);
  assert.match(guide, /One-day execution sequence/);
  assert.match(guide, /Technical portfolio/);
  assert.match(guide, /## Question 1/);
  assert.match(guide, /## Question 6/);
  assert.match(guide, /KV bytes = batch/);
  assert.match(guide, /Data parallel[\s\S]*Does not reduce/);
  assert.ok((guide.match(/```mermaid/g) ?? []).length >= 4);
  assert.equal(publishedGuide, guide);
});

test("publishes the WSL agent and host-to-device trace plan", async () => {
  const app = await readFile(new URL("../src/App.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/styles.css", root), "utf8");
  const guide = await readFile(new URL("../docs/WSL_AGENT_HOST_DEVICE_DEBUGGING.md", root), "utf8");
  const publishedGuide = await readFile(new URL("WSL_AGENT_HOST_DEVICE_DEBUGGING.md", root), "utf8");
  const gdb = await readFile(new URL("../examples/gdb/quasar-host-device.gdb", root), "utf8");
  const launch = await readFile(new URL("../examples/vscode/launch.json", root), "utf8");
  assert.match(app, /Native agents, one Linux toolchain/);
  assert.match(app, /0x400254: 0x4005a00b/);
  assert.match(app, /agentHostDeviceFlow/);
  assert.match(styles, /\.agent-debug-workbench/);
  assert.match(styles, /\.host-device-trace/);
  assert.match(guide, /## Logic review/);
  assert.match(guide, /Rejected premises/);
  assert.match(guide, /program_run_args\.cpp:704/);
  assert.match(guide, /0x400254.*4005a00b/);
  assert.match(guide, /K0.*K1.*K2.*K3/s);
  assert.match(gdb, /program\.cpp:2211/);
  assert.match(gdb, /define tt-host-state/);
  assert.match(launch, /TT_METAL_CACHE/);
  assert.equal(publishedGuide, guide);
});

test("documents the verified Blackhole smoke test", async () => {
  const app = await readFile(new URL("../src/App.tsx", root), "utf8");
  const record = await readFile(new URL("../docs/BLACKHOLE_SMOKE_TEST.md", root), "utf8");
  assert.match(app, /id="verified"/);
  assert.match(app, /50a82f83559/);
  assert.match(app, /device_id=0xb140/);
  assert.match(app, /Dispatch telemetry SMC buffer unavailable/);
  assert.match(app, /--build-programming-examples/);
  assert.match(record, /RESULT: PASS/);
  assert.match(record, /Success: Result is 21/);
});

test("includes the layered mechanism debugging guide", async () => {
  const app = await readFile(new URL("../src/App.tsx", root), "utf8");
  const guide = await readFile(new URL("../docs/TTSIM_DEBUGGING_PATH.md", root), "utf8");
  const publishedGuide = await readFile(new URL("TTSIM_DEBUGGING_PATH.md", root), "utf8");
  const launch = await readFile(new URL("../examples/vscode/launch.json", root), "utf8");
  assert.match(app, /id="debug"/);
  assert.match(app, /Follow one value through the machine/);
  assert.match(app, /Read and follow/);
  assert.match(app, /Single-core matmul debugging lab/);
  assert.match(app, /Compute engines and Tensix data flow/);
  assert.match(app, /gdb: command not found/);
  assert.match(app, /BH VERIFIED/);
  assert.match(app, /two header lines and no TEST-FULL zones/);
  assert.match(guide, /Host C\+\+ is a normal Linux process/);
  assert.match(guide, /BRISC, NCRISC, TRISC0, TRISC1 and TRISC2/);
  assert.match(guide, /TR0.*TR1.*TR2/);
  assert.match(guide, /UnimplementedFunctionality: rv64_custom_0: funct3=2/);
  assert.match(guide, /tt::watcher::dump\(stderr, true\)/);
  assert.match(guide, /only 125 scopes per core/);
  assert.match(guide, /CSV contained only/);
  assert.match(launch, /build-debug\/test\/tt_metal\/unit_tests_legacy/);
  assert.match(launch, /libttsim_qsr\.so/);
  assert.equal(publishedGuide, guide);
});

test("documents detailed Blackhole and Quasar simulation sequences", async () => {
  const app = await readFile(new URL("../src/App.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/styles.css", root), "utf8");
  const record = await readFile(new URL("../docs/SIMULATION_SEQUENCE.md", root), "utf8");
  assert.match(app, /id="sequences"/);
  assert.match(app, /Blackhole TT-Sim successful execution sequence/);
  assert.match(app, /Quasar TT-Sim successful execution sequence/);
  assert.match(app, /rv64_custom_0/);
  assert.match(app, /0x12345678/);
  assert.match(styles, /\.sequence-svg/);
  assert.match(styles, /\.detour-flow/);
  assert.match(record, /sequenceDiagram/);
  assert.match(record, /device_id=0xb140/);
  assert.match(record, /device_id=0xfeed/);
  assert.match(record, /NOC_API_V2/);
});

test("explains Quasar clusters and ships a repeatable architecture lab", async () => {
  const app = await readFile(new URL("../src/App.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/styles.css", root), "utf8");
  const guide = await readFile(new URL("../docs/QUASAR_CLUSTER_LAB.md", root), "utf8");
  const script = await readFile(new URL("../scripts/03-quasar-cluster-lab.sh", root), "utf8");
  assert.match(app, /id="architecture"/);
  assert.match(app, /Quasar is cluster-oriented/);
  assert.match(app, /8 DM cores/);
  assert.match(app, /4 Tensix Neo engines/);
  assert.match(app, /4 MiB shared SRAM/);
  assert.match(app, /DM0–DM1 are reserved/);
  assert.match(app, /8×4 rectangle/);
  assert.match(app, /MeshDevice/);
  assert.match(styles, /\.cluster-anatomy/);
  assert.match(styles, /\.architecture-table/);
  assert.match(guide, /cluster-oriented inside the chip/);
  assert.match(guide, /two separate passes/);
  assert.match(script, /QuasarMeshDeviceSingleCardFixture\.SingleDmL1Write/);
  assert.match(script, /architecture-report\.md/);
});

test("publishes the fused linear compiler and runtime capstone", async () => {
  const app = await readFile(new URL("../src/App.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/styles.css", root), "utf8");
  const guide = await readFile(new URL("../docs/COMPILER_RUNTIME_CAPSTONE.md", root), "utf8");
  const input = await readFile(new URL("../experiments/fused-linear-relu/input.mlir", root), "utf8");
  const expected = await readFile(new URL("../experiments/fused-linear-relu/expected.mlir", root), "utf8");
  const oracle = await readFile(new URL("../experiments/fused-linear-relu/oracle.py", root), "utf8");
  assert.match(app, /id="capstone"/);
  assert.match(app, /Y = ReLU\(A × B \+ bias\)/);
  assert.match(app, /const capstoneExperiments/);
  assert.match(app, /Recommended runtime lane/);
  assert.match(app, /Pre-silicon bring-up lane/);
  assert.match(styles, /\.capstone-roadmap/);
  assert.match(styles, /\.fusion-workbench/);
  assert.match(guide, /## The eight experiments/);
  assert.match(guide, /Simulator wall time predicts Blackhole silicon performance/);
  assert.match(input, /"lab\.matmul"/);
  assert.match(expected, /"lab\.fused_linear_relu"/);
  assert.match(oracle, /np\.testing\.assert_allclose/);
});

test("publishes the hardware-free contribution roadmap", async () => {
  const app = await readFile(new URL("../src/App.tsx", root), "utf8");
  const guide = await readFile(new URL("../docs/CONTRIBUTION_ROADMAP.md", root), "utf8");
  const publishedGuide = await readFile(new URL("CONTRIBUTION_ROADMAP.md", root), "utf8");
  assert.match(app, /id="contribute"/);
  assert.match(app, /Kernel first, compiler connected/);
  assert.match(app, /60%.*kernel.*40%.*compiler/is);
  assert.match(app, /TT-MLIR × TT-Metal/);
  assert.match(app, /TTIR → TTNN → FlatBuffer → ttrt → TT-Metal/);
  assert.match(app, /TTIR → D2M → TTKernel \+ TTMetal/);
  assert.match(app, /AI agents must not claim bounties/);
  assert.match(guide, /Route simulator findings to the correct repository/);
  assert.match(guide, /How TT-MLIR combines with TT-Metal/);
  assert.match(guide, /compiler-only, simulator-backed and hardware-verified evidence/);
  assert.match(guide, /TT-MLIR lit\/FileCheck coverage/);
  assert.match(guide, /tt-emule/);
  assert.equal(publishedGuide, guide);
});

test("publishes a guarded Wormhole, Blackhole and Quasar source comparison", async () => {
  const app = await readFile(new URL("../src/App.tsx", root), "utf8");
  const report = await readFile(new URL("../docs/TENSTORRENT_GENERATION_COMPARISON.md", root), "utf8");
  const publishedReport = await readFile(new URL("TENSTORRENT_GENERATION_COMPARISON.md", root), "utf8");
  const script = await readFile(new URL("../scripts/05-architecture-evidence.sh", root), "utf8");
  assert.match(app, /id="generations"/);
  assert.match(app, /Better is a vector, not a verdict/);
  assert.match(app, /Quasar is pre-silicon, binary-only/);
  assert.match(app, /PACK_COUNT=1/);
  assert.match(report, /Quasar is not publicly proven faster than Blackhole/);
  assert.match(report, /28 Blackhole-only paths/);
  assert.match(report, /Not supported.*Quasar is already faster/s);
  assert.match(script, /Blackhole-only vs Wormhole/);
  assert.match(script, /early bring-up/);
  assert.equal(publishedReport, report);
});

test("builds a dedicated Blackhole versus Huawei Ascend page", async () => {
  const html = await readFile(new URL("huawei.html", root), "utf8");
  const app = await readFile(new URL("../src/HuaweiApp.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/huawei.css", root), "utf8");
  const report = await readFile(new URL("../docs/BLACKHOLE_VS_HUAWEI_ASCEND.md", root), "utf8");
  const publishedReport = await readFile(new URL("BLACKHOLE_VS_HUAWEI_ASCEND.md", root), "utf8");
  assert.match(html, /Blackhole × Huawei Ascend/);
  assert.match(html, /(?:src|href)="\.\/assets\//);
  assert.match(app, /HBM is one axis/);
  assert.match(app, /not silently assigned to 910B\/910C/);
  assert.match(app, /144 GB \/ 4 TB\/s HBM/);
  assert.match(app, /What can Huawei learn from Tenstorrent's architecture/);
  assert.match(app, /Where is Huawei more advanced in architecture and performance/);
  assert.match(app, /784 GB\/s bidirectional D2D/);
  assert.match(app, /No public same-model, same-precision, same-power benchmark/);
  assert.match(styles, /\.flow-pair/);
  assert.match(styles, /\.comparison-table/);
  assert.match(styles, /\.qa-grid/);
  assert.match(report, /There is no architecture-only winner/);
  assert.match(report, /future vendor roadmap/);
  assert.match(report, /32 GB HBM Gen2/);
  assert.match(report, /## Question 1: What can Huawei learn from Tenstorrent/);
  assert.match(report, /## Question 2: Where is Huawei more advanced than Tenstorrent/);
  assert.match(report, /No trustworthy public apples-to-apples benchmark/);
  assert.equal(publishedReport, report);
});

test("publishes the asynchronous kernel and matrix granularity field note", async () => {
  const html = await readFile(new URL("async-kernels.html", root), "utf8");
  const app = await readFile(new URL("../src/AsyncKernelsApp.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/async-kernels.css", root), "utf8");
  const report = await readFile(new URL("../docs/ASYNC_KERNELS_AND_MATRIX_GRANULARITY.md", root), "utf8");
  const publishedReport = await readFile(new URL("ASYNC_KERNELS_AND_MATRIX_GRANULARITY.md", root), "utf8");
  assert.match(html, /Async kernels × matrix granularity/);
  assert.match(html, /(?:src|href)="\.\/assets\//);
  assert.match(app, /Async is a.*contract/);
  assert.match(app, /8×16/);
  assert.match(app, /16 MVMUL/);
  assert.match(app, /SetFlag \/ WaitFlag/);
  assert.match(styles, /\.scope-workbench/);
  assert.match(styles, /\.face-grid/);
  assert.match(report, /Four such issues cover a 32×16 region/);
  assert.match(report, /noc_async_writes_flushed/);
  assert.match(report, /16×32 × 32×16 → 16×16 output/);
  assert.match(report, /Huawei matrix granularity/);
  assert.equal(publishedReport, report);
});

test("publishes the host-to-RISC firmware and operation-kernel flow", async () => {
  const html = await readFile(new URL("firmware-flow.html", root), "utf8");
  const app = await readFile(new URL("../src/FirmwareFlowApp.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/firmware-flow.css", root), "utf8");
  const report = await readFile(new URL("../docs/RISC_FIRMWARE_TO_KERNEL_FLOW.md", root), "utf8");
  const publishedReport = await readFile(new URL("RISC_FIRMWARE_TO_KERNEL_FLOW.md", root), "utf8");
  assert.match(html, /Host to RISC firmware flow/);
  assert.match(html, /(?:src|href)="\.\/assets\//);
  assert.match(app, /Five RISCs/);
  assert.match(app, /No firmware relay/);
  assert.match(app, /DM0–DM7/);
  assert.match(app, /Run it twice/);
  assert.match(app, /step-sources/);
  assert.match(app, /risc_firmware_initializer\.cpp:1143–1199/);
  assert.match(app, /dispatch\.cpp:2355–2422/);
  assert.match(styles, /\.risc-sequence/);
  assert.match(styles, /\.phase-workbench/);
  assert.match(styles, /\.step-sources/);
  assert.match(report, /NCRISC is not a firmware relay/);
  assert.match(report, /ProgramBinaryStatus::Committed/);
  assert.match(report, /Chunk B1–B2/);
  assert.match(report, /Chunk R6–R8/);
  assert.match(report, /Direct code links for the B-markers/);
  assert.match(report, /Direct code links for the R-markers/);
  assert.match(report, /\[B4\] Multicast ELF spans/);
  assert.match(report, /\[R5\] Send GO/);
  assert.ok((report.match(/```mermaid/g) ?? []).length >= 10);
  assert.equal(publishedReport, report);
});

test("publishes the debugging and optimization discussion workbench", async () => {
  const html = await readFile(new URL("discussion.html", root), "utf8");
  const app = await readFile(new URL("../src/DiscussionApp.tsx", root), "utf8");
  const mainApp = await readFile(new URL("../src/App.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/discussion.css", root), "utf8");
  const guide = await readFile(new URL("../docs/DISCUSSION.md", root), "utf8");
  const publishedGuide = await readFile(new URL("DISCUSSION.md", root), "utf8");
  assert.match(html, /Discussion workbench/);
  assert.match(html, /(?:src|href)="\.\/assets\//);
  assert.match(app, /Loose notes now/);
  assert.match(app, /const topics/);
  assert.match(app, /Build a host-to-device stack trace recipe/);
  assert.match(app, /Measure cold versus warm Program traffic/);
  assert.match(app, /Filter by discussion track/);
  assert.match(app, /discussion-blackhole-bringup\.html/);
  assert.match(app, /discussion-transformer-blackhole-optimization\.html/);
  assert.match(app, /discussion-presentation\.html/);
  assert.match(app, /discussion-quantization\.html/);
  assert.match(app, /Optimize a Transformer on Blackhole/);
  assert.match(app, /Possible destination/);
  assert.match(mainApp, /href="\.\/discussion\.html"/);
  assert.match(styles, /\.topic-controls/);
  assert.match(styles, /\.promotion-path/);
  assert.match(guide, /## Debugging queue/);
  assert.match(guide, /## Optimization queue/);
  assert.match(guide, /## New-item template/);
  assert.match(guide, /question → reproducible observation → source evidence → conclusion → chapter/);
  assert.equal(publishedGuide, guide);
});

test("publishes the Blackhole BRISC NCRISC bring-up decision chain", async () => {
  const html = await readFile(new URL("discussion-blackhole-bringup.html", root), "utf8");
  const app = await readFile(new URL("../src/BlackholeBringupApp.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/blackhole-bringup.css", root), "utf8");
  const report = await readFile(new URL("../docs/DISCUSSION_BLACKHOLE_BRINGUP.md", root), "utf8");
  const publishedReport = await readFile(new URL("DISCUSSION_BLACKHOLE_BRINGUP.md", root), "utf8");
  assert.match(html, /Blackhole bring-up debug chain/);
  assert.match(html, /(?:src|href)="\.\/assets\//);
  assert.match(app, /Prove the .*boundary/s);
  assert.match(app, /there is no NCRISC→BRISC function call/);
  assert.match(app, /GW\/GD\/W\/R\/K\/KD\/D/);
  assert.match(app, /STAR \/ FIRST-SILICON SCENARIO/);
  assert.match(app, /Compiled ELF ≠ delivered bytes/);
  assert.match(app, /Add NCRISC-only data check/);
  assert.match(app, /C1 \/ TOOLCHAIN \+ LOAD IMAGE/);
  assert.match(app, /SFPI 7\.69\.0/);
  assert.match(app, /ELF32 · LE/);
  assert.match(app, /whole-file.*objcopy -O binary/s);
  assert.match(app, /MEM_MAX_KERNEL_SIZE/);
  assert.match(app, /R.*without.*K.*K.*without.*KD/s);
  assert.match(app, /TT_METAL_KERNEL_READBACK_ENABLE/);
  assert.match(app, /not blanket proof for Blackhole multicast writes/);
  assert.match(app, /All six must pass/);
  assert.match(app, /ROOT CAUSE OPEN/);
  assert.match(styles, /\.decision-workbench/);
  assert.match(styles, /\.observer-grid/);
  assert.match(app, /Choose the fact/);
  assert.match(app, /Huge pages are not device L1 or DRAM/);
  assert.match(styles, /\.handshake-flow/);
  assert.match(styles, /\.star-ladder/);
  assert.match(styles, /\.toolchain-flow/);
  assert.match(styles, /\.firmware-footprints/);
  assert.match(styles, /\.waypoint-definitions/);
  assert.match(report, /NCRISC does not call BRISC/);
  assert.match(report, /## STAR case study/);
  assert.match(report, /TensixTestEquivalentDataMovementKernelsWithDifferentProcessors/);
  assert.match(report, /Which toolchain built the ELF/);
  assert.match(report, /riscv-tt-elf-g\+\+ \(tenstorrent\/sfpi:7\.69\.0\[822\]\)/);
  assert.match(report, /ELF32.*little-endian.*RISC-V/s);
  assert.match(report, /whole-file `objcopy -O binary`/);
  assert.match(report, /R.*without.*K.*K.*without.*KD/s);
  assert.match(report, /two GO-bearing locations/i);
  assert.match(report, /subordinate_sync->dm1/);
  assert.match(report, /mailboxes->go_messages/);
  assert.match(app, /script_tng\.ld#L220-L244/);
  assert.doesNotMatch(app, /script_tng\.ld#L220-L250/);
  assert.match(report, /multicast readback is unsupported/);
  assert.match(report, /## Logic review of the plan/);
  assert.match(report, /## Code review of the plan/);
  assert.match(report, /TT_METAL_KERNEL_MAP=1/);
  assert.match(report, /Root-cause closure record/);
  assert.match(report, /not supplied/);
  assert.ok((report.match(/```mermaid/g) ?? []).length >= 16);
  assert.equal(publishedReport, report);
});

test("publishes the Blackhole fence semaphore and hardware-wait field guide", async () => {
  const html = await readFile(new URL("discussion-blackhole-synchronization.html", root), "utf8");
  const app = await readFile(new URL("../src/BlackholeSynchronizationApp.tsx", root), "utf8");
  const mainApp = await readFile(new URL("../src/App.tsx", root), "utf8");
  const discussionApp = await readFile(new URL("../src/DiscussionApp.tsx", root), "utf8");
  const bringupApp = await readFile(new URL("../src/BlackholeBringupApp.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/blackhole-synchronization.css", root), "utf8");
  const report = await readFile(new URL("../docs/DISCUSSION_BLACKHOLE_SYNCHRONIZATION.md", root), "utf8");
  const publishedReport = await readFile(new URL("DISCUSSION_BLACKHOLE_SYNCHRONIZATION.md", root), "utf8");
  assert.match(html, /Blackhole synchronization field guide/);
  assert.match(html, /(?:src|href)="\.\/assets\//);
  assert.match(app, /Fence is not/);
  assert.match(app, /Compiler-only fence/);
  assert.match(app, /Tensix hardware semaphore/);
  assert.match(app, /Payload first/);
  assert.match(app, /NWBW → NWBD/);
  assert.match(app, /TT_METAL_WATCHER_DEBUG_DELAY/);
  assert.match(app, /GDB\/JTAG/);
  assert.match(mainApp, /discussion-blackhole-synchronization\.html/);
  assert.match(discussionApp, /Select and debug Blackhole synchronization/);
  assert.match(bringupApp, /Sync field guide/);
  assert.match(styles, /\.sync-workbench/);
  assert.match(styles, /\.semaphore-compare/);
  assert.match(styles, /\.waypoint-console/);
  assert.match(report, /fence_compiler\(\).*emits no instruction/s);
  assert.match(report, /TTI_SEMWAIT/);
  assert.match(report, /16 program-visible slots/);
  assert.match(report, /16 IDs, `0…15`/);
  assert.match(report, /eight internal Tensix hardware semaphore IDs/);
  assert.match(report, /TT_METAL_CHECKPOINT=1/);
  assert.match(app, /16 IDs · 32-bit/);
  assert.match(report, /software polling/);
  assert.match(report, /noc_async_write_barrier\(\).*noc_semaphore_inc/s);
  assert.match(report, /absence finding/);
  assert.match(report, /## 8\. STAR scenario/);
  assert.ok((report.match(/```mermaid/g) ?? []).length >= 7);
  assert.equal(publishedReport, report);
});

test("publishes the Transformer on Blackhole optimization decision chain", async () => {
  const html = await readFile(new URL("discussion-transformer-blackhole-optimization.html", root), "utf8");
  const app = await readFile(new URL("../src/TransformerOptimizationApp.tsx", root), "utf8");
  const mainApp = await readFile(new URL("../src/App.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/transformer-optimization.css", root), "utf8");
  const report = await readFile(new URL("../docs/DISCUSSION_TRANSFORMER_BLACKHOLE_OPTIMIZATION.md", root), "utf8");
  const publishedReport = await readFile(new URL("DISCUSSION_TRANSFORMER_BLACKHOLE_OPTIMIZATION.md", root), "utf8");
  assert.match(html, /Transformer on Blackhole optimization chain/);
  assert.match(html, /(?:src|href)="\.\/assets\//);
  assert.match(app, /PLAN READY/);
  assert.match(app, /Two loops/);
  assert.match(app, /ttnn\.linear/);
  assert.match(app, /No invented/);
  assert.match(app, /D9/);
  assert.match(app, /MEASUREMENTS OPEN/);
  assert.match(app, /Forge compiles/);
  assert.match(app, /TT-Forge.*not.*tt-force/is);
  assert.match(app, /1\.5\.0\.dev20260819000359/);
  assert.match(app, /TTNN-IR \/ TTKernel-IR \/ TTMetal-IR/);
  assert.match(app, /01 · KV CACHE \+ ATTENTION/);
  assert.match(app, /Capability boundary/);
  assert.match(app, /numerical memory examples are explicitly Wormhole values/);
  assert.match(mainApp, /discussion-transformer-blackhole-optimization\.html/);
  assert.match(styles, /\.optimization-workbench/);
  assert.match(styles, /\.code-flow/);
  assert.match(styles, /\.compiler-release-strip/);
  assert.match(styles, /\.compiler-lever-matrix/);
  assert.match(styles, /\.measurement-table/);
  assert.match(report, /## Logic review of the plan/);
  assert.match(report, /## Code review of the plan/);
  assert.match(report, /Prefill and decode/);
  assert.match(report, /MatmulDeviceOperation/);
  assert.match(report, /measurements open/i);
  assert.match(report, /speedup remains intentionally unclaimed/);
  assert.match(report, /HF_MODEL=meta-llama\/Llama-3\.1-8B\r?\n/);
  assert.doesNotMatch(report, /HF_MODEL=meta-llama\/Llama-3\.1-8B-Instruct/);
  assert.match(report, /BFLOAT16, FLOAT32, BFLOAT8_B and/);
  assert.match(report, /## Compiler branch — where TT-Forge and TT-MLIR enter/);
  assert.match(report, /TT-Forge repository is the umbrella/);
  assert.match(report, /71046369d603b97fd6a8dd8b947ca8588ac2a74f/);
  assert.match(report, /How the four Transformer performance levers divide/);
  assert.match(report, /Do not combine a finding from the local pinned TTNN source/);
  assert.match(report, /TTNNPipelines\.cpp:100–158/);
  assert.match(report, /example capacity, latency and per-core budget numbers are Wormhole/);
  assert.ok((report.match(/```mermaid/g) ?? []).length >= 11);
  assert.equal(publishedReport, report);
});

test("publishes a source-backed 30-minute presentation room", async () => {
  const html = await readFile(new URL("discussion-presentation.html", root), "utf8");
  const app = await readFile(new URL("../src/PresentationApp.tsx", root), "utf8");
  const mainApp = await readFile(new URL("../src/App.tsx", root), "utf8");
  const discussionApp = await readFile(new URL("../src/DiscussionApp.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/presentation.css", root), "utf8");
  const report = await readFile(new URL("../docs/DISCUSSION_PRESENTATION_30_MIN.md", root), "utf8");
  const publishedReport = await readFile(new URL("DISCUSSION_PRESENTATION_30_MIN.md", root), "utf8");
  assert.match(html, /30-minute research presentation/);
  assert.match(html, /(?:src|href)="\.\/assets\//);
  assert.match(app, /A talk you can/);
  assert.match(app, /totalMinutes/);
  assert.match(app, /PERSONALIZE/);
  assert.match(app, /Cold firmware initialization and warm operation launch are different flows/);
  assert.match(app, /subordinate DM1 LOAD\/GO/);
  assert.match(app, /COPY ALL SLIDES/);
  assert.match(app, /Why do you say NCRISC does not call BRISC/);
  assert.match(app, /BACKUP \/ REFERENCES/);
  assert.match(app, /docs\.tenstorrent\.com\/tt-metal\/latest/);
  assert.match(app, /active\.sources\.map/);
  assert.match(app, /Official ttnn\.linear contract/);
  assert.match(mainApp, /discussion-presentation\.html/);
  assert.match(discussionApp, /SUBPAGE 04 · 30-MINUTE PRESENTATION/);
  assert.match(styles, /\.deck-workbench/);
  assert.match(styles, /\.boot-pair/);
  assert.match(report, /\*\*Total\*\* \| \*\*30 min\*\*/);
  assert.match(report, /The host places separate images/);
  assert.match(report, /historical compiler root-cause claim/);
  assert.match(report, /claim → strongest evidence → limitation → next experiment/);
  assert.match(report, /## Logic review/);
  assert.match(report, /## Code review/);
  assert.match(report, /## Slide-to-source map/);
  assert.match(report, /official Metalium tools index/i);
  assert.ok((report.match(/```mermaid/g) ?? []).length >= 7);
  assert.equal(publishedReport, report);
});

test("publishes the TTNN and TT-Metal LLM quantization decision guide", async () => {
  const html = await readFile(new URL("discussion-quantization.html", root), "utf8");
  const app = await readFile(new URL("../src/QuantizationApp.tsx", root), "utf8");
  const mainApp = await readFile(new URL("../src/App.tsx", root), "utf8");
  const discussionApp = await readFile(new URL("../src/DiscussionApp.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/quantization.css", root), "utf8");
  const report = await readFile(new URL("../docs/DISCUSSION_TT_METAL_QUANTIZATION.md", root), "utf8");
  const publishedReport = await readFile(new URL("DISCUSSION_TT_METAL_QUANTIZATION.md", root), "utf8");
  assert.match(html, /LLM quantization on TT-Metal/);
  assert.match(html, /(?:src|href)="\.\/assets\//);
  assert.match(app, /Start BF16/);
  assert.match(app, /An enum is not/);
  assert.match(app, /1,088 B \/ tile/);
  assert.match(app, /per-channel UINT8 output is rejected/);
  assert.match(app, /not a quantized matmul replacement/i);
  assert.match(app, /MXFP4/);
  assert.match(app, /DecodersPrecision\.accuracy/);
  assert.match(app, /format-references/);
  assert.match(app, /Official linear dtype table/);
  assert.match(app, /Quasar\/DFB MXFP4 test/);
  assert.match(app, /What are PTQ and QAT/);
  assert.match(app, /Calibration chooses a numeric mapping/);
  assert.match(app, /Symmetric or asymmetric quantization/);
  assert.match(app, /Min-max, percentile, or KL calibration/);
  assert.match(app, /pytorch\.org\/blog\/quantization-aware-training/);
  assert.match(app, /TensorRT calibration contract/);
  assert.match(app, /implicit quantization\/calibration workflow is deprecated/);
  assert.match(app, /Pinned TT-MLIR StableHLO Q\/DQ conversion/);
  assert.match(styles, /\.calibration-workbench/);
  assert.match(styles, /\.formula-grid/);
  assert.match(mainApp, /discussion-quantization\.html/);
  assert.match(discussionApp, /SUBPAGE 05 · LLM QUANTIZATION/);
  assert.match(styles, /\.format-workbench/);
  assert.match(styles, /\.quant-flow/);
  assert.match(styles, /\.logic-table/);
  assert.match(report, /Hardware\/LLK datatype capability/);
  assert.match(report, /BFLOAT8_B.*BFLOAT4_B/s);
  assert.match(report, /46\.875% less/);
  assert.match(report, /71\.875% less/);
  assert.match(report, /Do \*\*not\*\* start by changing every tensor to INT8/i);
  assert.match(report, /current generic \[`ttnn\.linear` contract\]/);
  assert.match(report, /## Logic review/);
  assert.match(report, /## Code review conclusions/);
  assert.match(report, /## Claim-to-reference map/);
  assert.match(report, /official Tensix compute-dataflow documentation/);
  assert.match(report, /## PTQ, QAT and calibration question chain/);
  assert.match(report, /Question 2 — why is calibration needed/);
  assert.match(report, /Asymmetric affine quantization/);
  assert.match(report, /entropy \/ KL divergence/);
  assert.match(report, /calibration chooses a numeric mapping; it does not create an/i);
  assert.match(report, /Question 6 — how do I implement affine quantization for a Tenstorrent LLM/);
  assert.match(report, /legacy calibration workflow—as deprecated/);
  assert.match(report, /real compiler quantization plumbing/);
  assert.ok((report.match(/```mermaid/g) ?? []).length >= 8);
  assert.equal(publishedReport, report);
});

test("provides a book-style chapter sidebar", async () => {
  const app = await readFile(new URL("../src/App.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/styles.css", root), "utf8");
  assert.match(app, /className="book-sidebar"/);
  assert.match(app, /Reading progress/);
  assert.match(app, /aria-current=.*location/);
  assert.match(app, /id="notebook"/);
  assert.match(styles, /\.book-sidebar\s*{[^}]*position:sticky/s);
  assert.match(styles, /\.chapters-open \.book-sidebar/);
});

test("uses relative built asset paths for project Pages", async () => {
  const html = await readFile(new URL("index.html", root), "utf8");
  assert.match(html, /(?:src|href)="\.\/assets\//);
});

test("ships a persistent system-aware light and dark theme", async () => {
  const html = await readFile(new URL("index.html", root), "utf8");
  const app = await readFile(new URL("../src/App.tsx", root), "utf8");
  const styles = await readFile(new URL("../src/styles.css", root), "utf8");
  assert.match(html, /ttsim-theme/);
  assert.match(html, /prefers-color-scheme: dark/);
  assert.match(app, /className="theme-toggle"/);
  assert.match(app, /localStorage\.setItem\("ttsim-theme"/);
  assert.match(styles, /:root\[data-theme="light"\]/);
});
