export const qaCategories = [
  "Architecture & performance",
  "Memory & dataflow",
  "Transformers & LLMs",
  "Quantization & precision",
  "Compiler & runtime",
  "Scheduling & scaling",
  "Evidence & leadership",
] as const;

export type QACategory = (typeof qaCategories)[number];

export type QASource = { label: string; href: string };

export type QAItem = {
  id: number;
  category: QACategory;
  question: string;
  answer: string;
  deeper: string;
  proof: string;
  memory: string;
  sources: readonly QASource[];
};

const commit = "50a82f835593512c4176546b4af68d7e91315a86";
const ttMetal = `https://github.com/tenstorrent/tt-metal/blob/${commit}`;

const source = {
  profiler: "https://docs.tenstorrent.com/tt-metal/latest/tt-metalium/tools/device_program_profiler.html",
  ttnnProfiler: "https://docs.tenstorrent.com/tt-metal/latest/ttnn/ttnn/profiling_ttnn_operations.html",
  tensix: "https://docs.tenstorrent.com/tt-metal/latest/tt-metalium/tt_metal/advanced_topics/compute_engines_and_dataflow_within_tensix.html",
  tensor: "https://docs.tenstorrent.com/tt-metal/latest/ttnn/ttnn/tensor.html",
  linear: "https://docs.tenstorrent.com/tt-metal/latest/ttnn/ttnn/api/ttnn.linear.html",
  tools: "https://docs.tenstorrent.com/tt-metal/latest/tt-metalium/tools/index.html",
  cb: `${ttMetal}/tt_metal/hw/inc/api/dataflow/dataflow_api.h#L832-L1223`,
  noc: `${ttMetal}/tt_metal/hw/inc/api/dataflow/dataflow_api.h#L1743-L1917`,
  modelPrecision: `${ttMetal}/models/tt_transformers/tt/model_config.py#L128-L237`,
  modelConfig: `${ttMetal}/models/tt_transformers/tt/model_config.py#L528-L680`,
  sdpa: `${ttMetal}/ttnn/cpp/ttnn/operations/transformer/sdpa_decode/sdpa_decode.cpp#L41-L178`,
  sdpaFactory: `${ttMetal}/ttnn/cpp/ttnn/operations/transformer/sdpa_decode/device/sdpa_decode_program_factory.cpp#L510-L1035`,
  cann: "https://www.hiascend.com/document/detail/en/canncommercial/850/opdevg/Ascendcopdevg/atlas_ascendc_map_10_0004.html",
  cannPerf: "https://www.hiascend.com/document/detail/en/CANNCommunityEdition/850/opdevg/Ascendcopdevg/atlas_ascendc_best_practices_10_0001.html",
  mindspore: "https://www.mindspore.cn/tutorials/en/stable/beginner/introduction.html",
  portfolio: "https://bui-cong-nguyen-acim.piernd2.chatgpt.site",
  performance: "https://bui-cong-nguyen-acim.piernd2.chatgpt.site/performance-method",
  resume: "https://bui-cong-nguyen-acim.piernd2.chatgpt.site/BuiCongNguyen_ResumeEN_202607.pdf",
  ttsim: "https://github.com/tenstorrent/ttsim",
} as const;

const src = (label: string, href: string): QASource => ({ label, href });

export const qaItems = [
  {
    id: 1,
    category: "Architecture & performance",
    question: "The model is slow. What do you do first?",
    answer: "I first define what ‘slow’ means: time-to-first-token, inter-token latency, throughput, tail latency, or energy per token. Then I freeze the workload, precision, software revision, warm-up, and correctness gate; profile the full path; localize the first limiting boundary; change one mechanism; and measure again.",
    deeper: "I separate host and dispatch gaps, layout conversion, compute, external memory, local memory, NoC or collectives, synchronization, and shape-tail waste. Jumping immediately to more HBM, more cores, or quantization is guessing before the problem is classified.",
    proof: "Same warm workload, repeated measurements, profiler signature, retained correctness, and a predeclared rollback gate.",
    memory: "Define → freeze → measure → localize → change one thing → prove.",
    sources: [src("TTNN operation profiling", source.ttnnProfiler), src("Performance method", source.performance)],
  },
  {
    id: 2,
    category: "Architecture & performance",
    question: "How do you determine whether a workload is memory-bound or compute-bound?",
    answer: "I combine a roofline model with measured counters. Arithmetic intensity predicts whether the workload needs more compute or bandwidth; sustained compute, bytes per second, queue stalls, and stage timing show which ceiling is actually reached during the named phase.",
    deeper: "I use separate intensities for external memory and local SRAM because a workload can reuse data well from DRAM yet still stall on local banks, NoC delivery, or unpack/pack. Low compute utilization alone does not prove a compute shortage; it may show that the current compute cannot be fed.",
    proof: "Move arithmetic intensity or bandwidth in a controlled microbenchmark and verify that performance follows the predicted roofline branch.",
    memory: "Model the ceiling; measure the stall; perturb the suspected limit.",
    sources: [src("Device Program Profiler", source.profiler), src("Tensix dataflow", source.tensix)],
  },
  {
    id: 3,
    category: "Architecture & performance",
    question: "With fixed silicon area, should you add compute, SRAM, or memory bandwidth?",
    answer: "I would not decide from a headline utilization number. I would freeze the workload mix and SLO, classify each phase by compute, capacity, bandwidth, communication, latency, or power, then sweep balanced options under equal area and power and choose the smallest change that improves the weighted workload.",
    deeper: "More compute helps only when operands arrive on time. More SRAM helps only when it captures a reusable working set. More external bandwidth helps when required traffic remains after reuse work, but PHY, die-edge, package, board, memory cost, and I/O power do not trade like an ordinary core block.",
    proof: "Weighted P50/P99 latency and throughput improve while power, thermals, package cost, area, and compiler mapping remain inside constraints.",
    memory: "Spend area on the measured weighted bottleneck—not the lowest utilization.",
    sources: [src("Architecture workbench", "./discussion-architecture-interview.html"), src("Profiler", source.profiler)],
  },
  {
    id: 4,
    category: "Architecture & performance",
    question: "Why does HBM help?",
    answer: "HBM raises available external-memory bandwidth and often capacity, so it can feed bandwidth-limited weights, activations, and KV data faster. It is most valuable when the workload has unavoidable external traffic and the rest of the system can consume the additional bandwidth.",
    deeper: "HBM does not increase arithmetic intensity, repair poor tiling, eliminate redundant transfers, fix NoC congestion, or remove synchronization. Peak bandwidth is not sustained bandwidth, and package pins, controllers, access shape, bank behavior, and power can prevent the cores from seeing the advertised number.",
    proof: "Show external bandwidth near its sustainable limit before the change and a corresponding drop in memory-stall time after the change.",
    memory: "HBM raises the byte ceiling; it does not remove bytes.",
    sources: [src("Tensix dataflow", source.tensix), src("Profiler", source.profiler)],
  },
  {
    id: 5,
    category: "Architecture & performance",
    question: "Can HBM itself become the bottleneck?",
    answer: "Yes. If the workload's required external bytes per second approaches sustained controller bandwidth, compute units wait even though peak TOPS remains unused. Decode can expose this because weights and KV state may move for relatively little arithmetic per generated token.",
    deeper: "I check bandwidth per phase, not a whole-model average. I also distinguish controller saturation from ineffective bandwidth caused by small transactions, poor coalescing, imbalance, routing, serialization, or insufficient request concurrency.",
    proof: "Bandwidth is near the measured sustainable limit, memory wait dominates, and reducing bytes improves performance while adding compute does not.",
    memory: "Peak compute is irrelevant when required bytes exceed sustained bytes.",
    sources: [src("TTNN profiling", source.ttnnProfiler), src("Transformer model configuration", source.modelConfig)],
  },
  {
    id: 6,
    category: "Architecture & performance",
    question: "HBM bandwidth is already saturated. How do you improve performance?",
    answer: "I stop asking how to feed more traffic and ask which bytes can disappear. I compare better tiling and reuse, fusion, compression or lower precision, multicast, KV locality, recomputation, and partition changes; only unavoidable traffic justifies more raw memory bandwidth.",
    deeper: "Every option has a cost. Reuse consumes local capacity, fusion lengthens live ranges, compression adds conversion and quality risk, and recomputation trades bytes for arithmetic. I choose the lowest-risk option that reduces the measured traffic on the critical phase.",
    proof: "External bytes and memory-stall time fall by the predicted amount while quality, local-memory fit, occupancy, and end-to-end SLO remain valid.",
    memory: "When bandwidth is full, remove bytes before buying bandwidth.",
    sources: [src("Tensix dataflow", source.tensix), src("Precision policy", source.modelPrecision)],
  },
  {
    id: 7,
    category: "Architecture & performance",
    question: "What is the difference between latency, throughput, utilization, power, and energy?",
    answer: "Latency is time for a request or phase; throughput is completed work per unit time; utilization is the fraction of a resource doing useful work; power is instantaneous energy rate; energy is power integrated over time. They are related, but optimizing one does not guarantee the others improve.",
    deeper: "Batching can raise throughput and utilization while hurting queueing latency. Lower frequency can reduce watts but increase joules per request if runtime grows too much. I therefore optimize against an explicit service-level objective rather than a single convenient counter.",
    proof: "Report all relevant metrics on the same workload boundary, including P50/P99 latency and steady-state power or energy per token.",
    memory: "Name the objective; do not substitute a proxy for the product SLO.",
    sources: [src("Device profiler", source.profiler), src("Performance method", source.performance)],
  },
  {
    id: 8,
    category: "Architecture & performance",
    question: "Performance meets target, but power is over budget. What do you change?",
    answer: "I hold throughput and tail-latency requirements fixed, measure power by phase and subsystem, and rank avoidable activity. I first remove redundant movement and padded work, improve reuse and locality, then consider supported lower precision, clock or power gating, rebalancing, and the lowest DVFS point that still meets the SLO.",
    deeper: "I distinguish peak power, average power, thermal steady state, and energy per request. Lowering watts is not automatically a win if execution becomes long enough to consume more joules or miss latency.",
    proof: "Named power method, sustained thermal run, energy per token, unchanged quality, and throughput/P99 still inside budget.",
    memory: "Remove useless activity first; lower voltage only with SLO headroom.",
    sources: [src("Profiler", source.profiler), src("Precision policy", source.modelPrecision)],
  },
  {
    id: 9,
    category: "Memory & dataflow",
    question: "Why use SRAM or local memory instead of reading everything from HBM?",
    answer: "Local memory provides much higher effective bandwidth and lower latency and energy for the working set nearest compute. Its architectural value comes from reuse: load a tile once, use it many times, and avoid repeated external traffic.",
    deeper: "Capacity alone is not a benefit. The compiler and kernel must choose a tile, layout, bank mapping, and lifetime that fit inputs, accumulators, output staging, metadata, and possibly two buffer generations. Oversized local storage can cost area, routing, access time, and compute count.",
    proof: "External bytes fall, local access remains conflict-free, the full live set fits with headroom, and compute wait decreases.",
    memory: "SRAM pays only when software turns capacity into reuse.",
    sources: [src("Tensix compute dataflow", source.tensix), src("Tensor layouts", source.tensor)],
  },
  {
    id: 10,
    category: "Memory & dataflow",
    question: "What is tiling?",
    answer: "Tiling partitions a larger tensor operation into blocks that fit the target's local storage and compute geometry. A good tile exposes data reuse and parallelism while controlling padding, tails, banking, communication, and accumulator lifetime.",
    deeper: "Tile size is constrained by datatype, shape, array geometry, local capacity, double buffers, alignment, circular-buffer metadata, and writer staging. The largest tile is not automatically best; it may reduce occupancy, parallelism, or load balance.",
    proof: "A capacity equation predicts fit, measured bytes match expected reuse, tails remain correct, and the stage pipeline becomes faster.",
    memory: "Tile to fit the live set—not merely to divide the loop.",
    sources: [src("Tensor layouts", source.tensor), src("Circular-buffer API", source.cb)],
  },
  {
    id: 11,
    category: "Memory & dataflow",
    question: "Why does double buffering help?",
    answer: "Double buffering keeps two generations of data so one can be consumed while the next is transferred. When reader, compute, and writer engines are independent, steady-state time can approach the slowest stage instead of the sum of all stages.",
    deeper: "It helps only if two generations fit, transfers truly overlap compute, and ownership is explicit. Incorrect reserve, push, wait, pop, or completion barriers can cause overwrite, stale reads, deadlock, or a larger buffer that lowers occupancy without creating overlap.",
    proof: "A device timeline shows overlap, stage wait shrinks, circular-buffer credits balance, and correctness survives stress and tail shapes.",
    memory: "Two buffers enable overlap; ownership and independent engines create it.",
    sources: [src("Circular-buffer contract", source.cb), src("Typed NoC barriers", source.noc)],
  },
  {
    id: 12,
    category: "Memory & dataflow",
    question: "What is prefetching, and when can it hurt?",
    answer: "Prefetching issues a future data transfer early enough to hide its latency behind useful work. It hurts when the prefetched data is not used, arrives too early and occupies scarce buffers, competes for bandwidth with critical traffic, or increases synchronization and cache pollution.",
    deeper: "I choose prefetch distance from measured transfer and compute times, queue depth, working-set capacity, and address predictability. More distance is not always safer because it expands the live set and can create backpressure.",
    proof: "Transfer wait decreases without increasing total bytes, buffer pressure, eviction, congestion, or tail latency.",
    memory: "Prefetch just in time—early enough to hide, late enough to fit.",
    sources: [src("Tensix dataflow", source.tensix), src("NoC API", source.noc)],
  },
  {
    id: 13,
    category: "Memory & dataflow",
    question: "What role does DMA or asynchronous data transfer play in an NPU?",
    answer: "DMA moves data between memory domains without tying up the main compute path instruction by instruction. Asynchronous transfer allows movement to overlap compute, but the program still needs correct addresses, sizes, routing, completion, publication, and buffer ownership.",
    deeper: "I separate issue, flush, completion, and consumer visibility. A transfer being queued or departed does not necessarily mean remote data is complete and safe to publish. This distinction is central to both performance and intermittent correctness bugs.",
    proof: "Timeline and waypoints show issue-to-completion ordering, the consumer never sees partial data, and overlap improves warm end-to-end time.",
    memory: "Async starts work; a typed completion edge makes data safe.",
    sources: [src("Typed NoC barriers", source.noc), src("Synchronization guide", "./discussion-blackhole-synchronization.html")],
  },
  {
    id: 14,
    category: "Memory & dataflow",
    question: "How do you keep compute units busy?",
    answer: "I balance the full producer–compute–consumer pipeline. That may require larger or better-shaped work, compatible layouts, enough in-flight transfers, double buffering, multicast or reuse, balanced sharding, reduced dispatch gaps, and fewer synchronization stalls.",
    deeper: "I do not optimize utilization in isolation. Batching can fill the array but hurt latency and memory; more cores can increase communication; deep buffers can consume SRAM. The correct target is useful work that improves the declared SLO.",
    proof: "Per-stage timelines show less starvation and backpressure, useful compute rises, and end-to-end latency or throughput improves.",
    memory: "Feed, balance, and drain the pipeline—then check the product metric.",
    sources: [src("Tensix dataflow", source.tensix), src("TTNN profiling", source.ttnnProfiler)],
  },
  {
    id: 15,
    category: "Memory & dataflow",
    question: "When is operator fusion beneficial?",
    answer: "Fusion is beneficial when it removes an expensive intermediate memory boundary or repeated dispatch without creating a worse local-capacity or scheduling problem. MatMul → bias → activation is a classic candidate when the result can remain local through the epilogue.",
    deeper: "I quantify which intermediate bytes and launches disappear, whether layouts are compatible, and how long accumulators and temporary values remain live. The benefit depends on shape, precision, local capacity, kernel support, and reuse—not just graph adjacency.",
    proof: "Intermediate DRAM or NoC bytes and launches fall while spills, occupancy, code size, correctness, and warm latency stay acceptable.",
    memory: "Fuse to remove a measured boundary.",
    sources: [src("Transformer optimization chain", "./discussion-transformer-blackhole-optimization.html"), src("Profiler", source.profiler)],
  },
  {
    id: 16,
    category: "Memory & dataflow",
    question: "When can operator fusion hurt?",
    answer: "Fusion can hurt when the combined live set spills, local memory limits occupancy, code size grows, register pressure rises, one large kernel loses producer–consumer parallelism, layouts conflict, or recomputation and synchronization exceed the saved traffic.",
    deeper: "It can also reduce compiler flexibility: independently scheduled operators may map better to different core grids or overlap with other work. I compare fused and unfused plans on the real shape distribution rather than treating fusion as a rule.",
    proof: "Check local-memory high-water mark, spills, occupancy, stage overlap, code size, compile time, correctness, and end-to-end performance.",
    memory: "Stop fusing when saved traffic costs more live state or parallelism.",
    sources: [src("Transformer optimization chain", "./discussion-transformer-blackhole-optimization.html"), src("TTNN profiling", source.ttnnProfiler)],
  },
  {
    id: 17,
    category: "Transformers & LLMs",
    question: "Why is attention expensive?",
    answer: "Attention combines large matrix products, softmax, and data movement whose cost grows strongly with sequence length. A naïve implementation materializes a large score matrix, repeatedly moving intermediate data between slow and fast memory.",
    deeper: "The dominant limit depends on phase and shape. Prefill exposes larger matrix operations and score work; autoregressive decode reuses cached keys and values but may become dominated by KV and weight movement, small-M kernels, and launch overhead.",
    proof: "Profile QKᵀ, softmax, V multiplication, intermediate bytes, and sequence-length scaling separately for prefill and decode.",
    memory: "Attention cost is math plus an often larger intermediate-data problem.",
    sources: [src("SDPA decode validation", source.sdpa), src("SDPA program factory", source.sdpaFactory)],
  },
  {
    id: 18,
    category: "Transformers & LLMs",
    question: "What is the architectural idea behind FlashAttention?",
    answer: "The key idea is to tile attention so the large score matrix is not repeatedly written to and read from slower memory. Blocks of Q, K, and V stay in faster memory while softmax statistics are updated online, reducing external traffic without changing the mathematical result beyond numerical-order effects.",
    deeper: "The implementation must respect local capacity, numerical stability, causal masking, tails, and pipeline balance. It is an I/O-aware algorithm: the speedup comes from a different data-movement schedule, not from deleting the attention computation.",
    proof: "Intermediate bytes fall, output matches the reference within tolerance, and speedup follows sequence length and memory pressure as predicted.",
    memory: "Do the same attention without materializing the expensive matrix boundary.",
    sources: [src("SDPA program factory", source.sdpaFactory), src("Tensix dataflow", source.tensix)],
  },
  {
    id: 19,
    category: "Transformers & LLMs",
    question: "Why does KV cache exist?",
    answer: "During autoregressive generation, earlier keys and values do not change. KV cache stores them so each new token attends to prior context without recomputing every earlier layer state from scratch.",
    deeper: "The trade-off is capacity and bandwidth. Cache size scales with batch, tokens, layers, two tensors, KV heads, head dimension, and bytes per value. Variable sequence lengths also introduce reservation waste, fragmentation, indirection, and concurrency pressure.",
    proof: "Build the exact checkpoint memory ledger and measure cache bytes, hit/use pattern, bandwidth, allocation waste, and inter-token latency.",
    memory: "KV cache trades repeated compute for growing memory state.",
    sources: [src("Transformer configuration", source.modelConfig), src("SDPA decode", source.sdpa)],
  },
  {
    id: 20,
    category: "Transformers & LLMs",
    question: "What is the difference between MHA, MQA, and GQA?",
    answer: "Multi-head attention gives each query head its own key and value heads. Multi-query attention shares one key/value head across many query heads. Grouped-query attention uses fewer KV heads than query heads, forming a middle point between capacity/bandwidth reduction and model quality or expressiveness.",
    deeper: "The choice directly changes KV-cache size and traffic, but the exact performance also depends on kernel layout, head grouping, sharding, batch, context, and supported implementation. I never estimate KV size from parameter count alone.",
    proof: "Use the exact query/KV head counts in the cache formula, then compare quality and decode bandwidth on supported kernels.",
    memory: "Fewer KV heads shrink cache and traffic; quality and kernel mapping decide the trade.",
    sources: [src("Transformer configuration", source.modelConfig), src("SDPA decode", source.sdpa)],
  },
  {
    id: 21,
    category: "Transformers & LLMs",
    question: "How would you optimize Transformer inference?",
    answer: "I split prefill and decode, define TTFT, inter-token latency, and throughput goals, then profile operator and communication time. For prefill I usually inspect large GEMM, attention tiling, fusion, and compute mapping; for decode I inspect weight/KV traffic, small-M efficiency, batching, cache layout, and launch overhead.",
    deeper: "I then compare supported precision by tensor role, layout and sharding, paged KV management, program cache or trace reuse, and multi-device partitioning. Each change keeps a model-quality gate and the same request distribution.",
    proof: "Separate prefill/decode profiles, warm runs, tokens/s, TTFT, ITL, bytes, utilization, quality, and collective time.",
    memory: "Split the phase, find the boundary, optimize the bytes or math that dominate it.",
    sources: [src("Transformer optimization chain", "./discussion-transformer-blackhole-optimization.html"), src("Precision policy", source.modelPrecision)],
  },
  {
    id: 22,
    category: "Transformers & LLMs",
    question: "Why must prefill and decode be analyzed separately?",
    answer: "Prefill processes many input tokens together and often maps to larger, more compute-efficient matrix operations. Decode processes one or a few new tokens per request, so small-M kernels, weight and KV movement, synchronization, and launch overhead can dominate.",
    deeper: "An optimization that raises prefill throughput may hurt inter-token latency through larger batches or more memory state. A single average hides the two operating points and can lead to a design that is excellent for one phase and poor for the other.",
    proof: "Report TTFT and prefill tokens/s separately from inter-token latency and decode tokens/s across the real batch/context distribution.",
    memory: "Prefill is not decode; optimize two shapes and two SLOs.",
    sources: [src("Transformer configuration", source.modelConfig), src("TTNN profiling", source.ttnnProfiler)],
  },
  {
    id: 23,
    category: "Transformers & LLMs",
    question: "A 7B model works well, but a 70B model does not. What do you investigate?",
    answer: "I first define the failure: cannot load, out of memory, slow prefill, slow decode, or poor multi-chip scaling. Then I build a complete memory ledger; raw 70B weights alone are about 140 GB at 16-bit, 70 GB at 8-bit, or 35 GB at 4-bit before scales, padding, runtime buffers, and KV cache.",
    deeper: "If it does not fit, I choose supported precision and partitioning before tuning kernels. If decode is slow, I profile weight/KV bytes and small-M efficiency. If single-device phases are healthy but scaling is poor, I inspect partition, collectives, link utilization, overlap, and imbalance.",
    proof: "Capacity headroom, quality, TTFT, ITL, tokens/s, and communication scaling each pass their own gate.",
    memory: "Define the failure; capacity before kernels; phase before optimization.",
    sources: [src("Transformer configurations", source.modelConfig), src("Architecture workbench", "./discussion-architecture-interview.html")],
  },
  {
    id: 24,
    category: "Transformers & LLMs",
    question: "How do tensor, pipeline, and data parallelism differ for LLM inference?",
    answer: "Tensor parallelism splits work within a layer and pays frequent collective communication. Pipeline parallelism assigns layer groups to stages and pays activation transfers and bubbles. Data parallelism replicates the model for request throughput, so it does not solve the capacity of one replica.",
    deeper: "I choose from model fit, layer size, link topology, batch and microbatch availability, single-request latency, and throughput goals. Hybrid choices are common, but every added dimension increases scheduling, collective, and failure-management complexity.",
    proof: "Compare per-device capacity, communication bytes and time, bubbles, imbalance, TTFT, ITL, and aggregate throughput.",
    memory: "Tensor splits a layer; pipeline splits layers; data parallel copies the model.",
    sources: [src("Transformer configuration", source.modelConfig), src("Architecture workbench", "./discussion-architecture-interview.html")],
  },
  {
    id: 25,
    category: "Quantization & precision",
    question: "How does FP32-to-INT8 quantization work conceptually?",
    answer: "A scale maps a floating-point range into a limited integer code range; asymmetric quantization also uses a zero point so real zero is representable. Values are rounded and clipped, computation accumulates in a wider type, and results may be rescaled or dequantized.",
    deeper: "The numerical contract includes scale granularity, signedness, zero point, rounding, clipping, accumulator width, requantization, and kernel support. Storage reduction alone does not guarantee speedup if conversions, scale traffic, or unsupported fallbacks dominate.",
    proof: "Check float-oracle error, saturation, layer and task quality, supported kernel path, transferred bytes, and warm end-to-end time.",
    memory: "Format + scale + zero point + accumulator + requantization = the real INT8 contract.",
    sources: [src("Quantization guide", "./discussion-quantization.html"), src("TTNN linear contract", source.linear)],
  },
  {
    id: 26,
    category: "Quantization & precision",
    question: "What is the difference between symmetric and asymmetric quantization?",
    answer: "Symmetric quantization centers the representable range around zero and commonly uses zero point zero, simplifying arithmetic. Asymmetric quantization shifts the integer range with a nonzero zero point, which can represent an offset distribution more efficiently but adds correction and metadata complexity.",
    deeper: "The better choice depends on tensor distribution, per-tensor versus per-channel scales, hardware kernels, and whether zero must be exact. Weights are often good symmetric candidates; nonnegative or shifted activations can benefit from asymmetric mapping if the target supports it efficiently.",
    proof: "Compare error, saturation, scale/zero-point overhead, kernel legality, conversion cost, and task quality.",
    memory: "Symmetric simplifies zero; asymmetric spends complexity to use the code range.",
    sources: [src("Quantization guide", "./discussion-quantization.html"), src("Precision policy", source.modelPrecision)],
  },
  {
    id: 27,
    category: "Quantization & precision",
    question: "What happens when MinMax calibration sees a few very large outliers?",
    answer: "MinMax stretches the scale to represent the full observed range. A few large outliers can therefore consume most of the code range and leave coarse resolution for the majority of values, increasing quantization error even though clipping is low.",
    deeper: "I compare percentile or clipping-based calibration, per-channel or group scales, outlier-aware decomposition, and selective higher precision. Clipping outliers is a trade: it improves common-value resolution but can damage rare, important activations.",
    proof: "Inspect distributions, saturation and error by layer, then validate logits, tokens, and task metrics on calibration and held-out data.",
    memory: "MinMax protects outliers by taxing everyone else's resolution.",
    sources: [src("Quantization guide", "./discussion-quantization.html"), src("Precision policy", source.modelPrecision)],
  },
  {
    id: 28,
    category: "Quantization & precision",
    question: "What is the difference between PTQ and QAT?",
    answer: "Post-training quantization calibrates and converts an already-trained model without retraining, so it is faster and cheaper but has less ability to recover accuracy. Quantization-aware training simulates quantization effects during training or fine-tuning so weights adapt, usually improving difficult low-precision cases at higher data and compute cost.",
    deeper: "I start with PTQ under a clear quality budget, identify sensitive layers and tensor roles, and use QAT only where calibration, mixed precision, or local fixes cannot meet the target. Deployment kernel support remains a separate requirement.",
    proof: "Same evaluation set, float baseline, task metric, training/calibration provenance, supported operator path, and end-to-end performance.",
    memory: "PTQ adapts scales; QAT lets the model adapt to the scales.",
    sources: [src("Quantization guide", "./discussion-quantization.html"), src("Precision policy", source.modelPrecision)],
  },
  {
    id: 29,
    category: "Quantization & precision",
    question: "Why are activation quantization and weight quantization different problems?",
    answer: "Weights are fixed after training and can be analyzed offline with per-channel or group scales. Activations depend on input, layer, token, and runtime state, so their ranges and outliers are harder to calibrate and may require dynamic scales or higher precision.",
    deeper: "Weights often dominate model storage and decode traffic, while activations can dominate error sensitivity, temporary memory, or prefill movement. I choose precision by tensor role rather than declaring the whole model INT8 or FP8.",
    proof: "Measure role-specific bytes, kernel support, conversion cost, distribution drift, layer error, and end-task quality.",
    memory: "Weights are stable storage; activations are dynamic behavior.",
    sources: [src("Precision policy", source.modelPrecision), src("Quantization guide", "./discussion-quantization.html")],
  },
  {
    id: 30,
    category: "Quantization & precision",
    question: "When would you choose FP8 instead of INT8?",
    answer: "I first name the exact FP8 format and INT8 scale policy. FP8 can be preferable when floating exponent range handles changing activation magnitudes with less calibration complexity, while INT8 can be excellent when per-channel or group scales fit the distribution and efficient integer kernels exist.",
    deeper: "The decision includes range, precision, outliers, scale metadata, conversion and requantization, accumulator type, kernel legality, memory bytes, and quality. Tenstorrent BFLOAT8_B is a block-floating format, not interchangeable with IEEE FP8 E4M3 or E5M2.",
    proof: "Run a per-role sweep with identical quality gates and warm end-to-end measurements; do not compare enum names alone.",
    memory: "Name the bits and scales before comparing the formats.",
    sources: [src("TTNN linear contract", source.linear), src("Precision policy", source.modelPrecision)],
  },
  {
    id: 31,
    category: "Quantization & precision",
    question: "What is mixed precision, and how do you choose precision islands?",
    answer: "Mixed precision assigns different formats to tensor roles or layers based on sensitivity and performance value. Lower precision can target large weights or bandwidth-heavy activations, while residual paths, normalization, softmax statistics, outlier layers, or accumulations remain at higher precision.",
    deeper: "I start from a stable baseline, lower one role at a time, and stop where quality or kernel support fails. Precision islands are valuable only if conversion boundaries do not erase the storage or throughput benefit.",
    proof: "Per-role ablation, conversion count, transferred bytes, supported kernels, layer error, task quality, and warm performance.",
    memory: "Spend high precision where error grows faster than performance value.",
    sources: [src("Transformer precision policy", source.modelPrecision), src("Quantization guide", "./discussion-quantization.html")],
  },
  {
    id: 32,
    category: "Compiler & runtime",
    question: "Explain the AI compiler flow from framework to NPU execution.",
    answer: "A model begins in a framework or exchange graph, enters an intermediate representation, undergoes semantic and graph optimization, quantization and layout decisions, then target-aware tiling, scheduling, placement, memory planning, and operator lowering produce kernels and runtime artifacts that dispatch on the NPU.",
    deeper: "At each stage I name the invariant and artifact: graph semantics, legal target operations, tensor layout, resource-fit schedule, bounded memory, generated binary, runtime command, and device trace. The exact stack may use ONNX, MLIR, a vendor IR, or direct framework integration, but the contracts remain similar.",
    proof: "Trace one operator through before/after IR, schedule, memory plan, generated kernel, runtime invocation, and numerical output.",
    memory: "Preserve semantics, expose target constraints, plan resources, lower, dispatch, prove.",
    sources: [src("Compiler/runtime presentation", "./discussion-presentation.html"), src("Portfolio compiler path", source.portfolio)],
  },
  {
    id: 33,
    category: "Compiler & runtime",
    question: "Why do constant folding and dead-code elimination matter?",
    answer: "Constant folding evaluates work whose inputs are known at compile time; dead-code elimination removes results that cannot affect observable output. Both reduce runtime operations, memory traffic, allocation, and scheduling pressure while preserving graph semantics.",
    deeper: "They must respect shape, side effects, numerical semantics, dynamic inputs, and target legality. Removing an operation is valuable not only for arithmetic but also because it can simplify layout, fusion, memory planning, and downstream placement.",
    proof: "Before/after IR shows the legal rewrite, output matches the oracle, and operation, allocation, or byte counts fall as predicted.",
    memory: "Do known work early; delete work that cannot be observed.",
    sources: [src("Compiler/runtime presentation", "./discussion-presentation.html"), src("Technical portfolio", source.portfolio)],
  },
  {
    id: 34,
    category: "Compiler & runtime",
    question: "What is operator lowering?",
    answer: "Operator lowering replaces a high-level semantic operation with target-supported operations, layouts, kernels, or instruction sequences. It bridges what the model means and what the hardware and runtime can legally execute.",
    deeper: "A good lowering preserves shape, datatype, numerical behavior, broadcasting, padding, and side effects while exposing tiling, memory, synchronization, and architecture-specific capabilities. Unsupported cases need a clear fallback or diagnostic, not a silent semantic change.",
    proof: "High-level and lowered outputs match across normal, boundary, and tail shapes; generated operations are legal for the target.",
    memory: "Lower meaning into legal machine work without losing the contract.",
    sources: [src("Compiler/runtime presentation", "./discussion-presentation.html"), src("TTNN tensor contract", source.tensor)],
  },
  {
    id: 35,
    category: "Compiler & runtime",
    question: "Why are layout transformations important on an NPU?",
    answer: "The hardware and kernels often require tiled, sharded, aligned, or bank-friendly layouts that differ from a framework's logical tensor view. Layout transformation makes data consumable by the target and can enable locality, multicast, parallelism, and supported kernels.",
    deeper: "Transformations are not free. Repeated tilize, untilize, reshard, transpose, padding, or host-device conversion can dominate small operations. I optimize layout across producer–consumer regions rather than each operator independently.",
    proof: "Operation trace shows fewer conversions and bytes while kernel legality, shape semantics, tails, and end-to-end performance remain correct.",
    memory: "Choose a layout for the region; do not pay conversion at every edge.",
    sources: [src("Tensor layouts", source.tensor), src("TTNN profiling", source.ttnnProfiler)],
  },
  {
    id: 36,
    category: "Compiler & runtime",
    question: "What does memory planning do?",
    answer: "Memory planning assigns storage, address, lifetime, alignment, and reuse for weights, activations, temporaries, communication buffers, and program state. It ensures the graph fits while reducing peak memory, fragmentation, copies, and allocation overhead.",
    deeper: "The planner uses liveness and alias rules but must respect asynchronous ownership: a buffer cannot be reused merely because host control has advanced if a device transfer or consumer still owns it. Dynamic shapes and KV state add reservation and fragmentation challenges.",
    proof: "Peak and allocated bytes match the plan, no live ranges overlap illegally, fragmentation is bounded, and correctness survives asynchronous stress.",
    memory: "Reuse storage only after the last real consumer returns ownership.",
    sources: [src("Tensor contract", source.tensor), src("Synchronization guide", "./discussion-blackhole-synchronization.html")],
  },
  {
    id: 37,
    category: "Compiler & runtime",
    question: "How do tiling, scheduling, and placement differ?",
    answer: "Tiling chooses the units of work and live data. Scheduling chooses execution order and overlap subject to dependencies and resources. Placement maps those scheduled operations and buffers onto physical cores, memory banks, and communication topology.",
    deeper: "They are coupled: a tile changes core-grid fit and traffic; placement changes communication; schedule changes lifetimes and memory. A principal-level optimizer iterates them with a cost model and verifies the final machine behavior rather than optimizing each stage in isolation.",
    proof: "Inspect tile and grid choices, dependency legality, resource fit, traffic, imbalance, memory high-water mark, and measured timeline.",
    memory: "Tile the work, order the work, map the work—then measure the coupling.",
    sources: [src("Tensix dataflow", source.tensix), src("Technical portfolio", source.portfolio)],
  },
  {
    id: 38,
    category: "Compiler & runtime",
    question: "How do you locate a bug across compiler, runtime, firmware, and kernel layers?",
    answer: "I find the first boundary where a known-good contract becomes wrong. I start with a small numerical oracle, inspect graph and lowered artifacts, verify runtime arguments and placement, then use operation traces, per-core profiler zones, Watcher or waypoints, DPRINT, and focused memory or NoC checks.",
    deeper: "I enable one intrusive debug mode at a time because instrumentation can perturb timing and shared memory. The first wrong tensor, missing waypoint, unbalanced circular-buffer credit, or incomplete transfer narrows ownership to a layer more reliably than reading the entire stack.",
    proof: "A minimized reproduction fails at one boundary, the fix moves or removes that first divergence, and the clean uninstrumented run remains correct.",
    memory: "Debug the first broken contract, not the last visible symptom.",
    sources: [src("Low-level debug atlas", "./debug-low-level-kernel-flow.html"), src("Metalium tools", source.tools)],
  },
  {
    id: 39,
    category: "Scheduling & scaling",
    question: "If an NPU has 16 cores, should you always use all 16?",
    answer: "No. More cores help only when the workload has enough parallel work and memory, communication, synchronization, and tails do not dominate. A smaller grid can improve locality, reduce multicast or collective cost, eliminate imbalance, and use scarce bandwidth more efficiently.",
    deeper: "I sweep core count and grid shape rather than assuming monotonic scaling. Decode, skinny matrices, small batches, uneven shards, and bandwidth-limited operators frequently expose diminishing or negative returns.",
    proof: "Per-core useful work, wait time, imbalance, bytes, barrier cost, bandwidth, power, and end-to-end SLO across the sweep.",
    memory: "Use the cores that add useful work faster than coordination cost.",
    sources: [src("Tensix dataflow", source.tensix), src("Profiler", source.profiler)],
  },
  {
    id: 40,
    category: "Scheduling & scaling",
    question: "How would you evaluate a new clustering strategy?",
    answer: "I define what clustering changes—core membership, local memory, routing, multicast, collective scope, fault domain, or scheduling—and freeze representative workloads and SLOs. Then I compare mapping quality, locality, communication, balance, utilization, power, and software complexity against a baseline.",
    deeper: "A strategy that wins one GEMM may lose a model portfolio or create compiler fragmentation. I include topology, tail shapes, mixed workloads, programmability, verification, and failure isolation rather than reporting only peak throughput.",
    proof: "Weighted workload improvement with stable correctness, power, thermal, area/cost assumptions, compiler coverage, and no hidden communication regression.",
    memory: "Evaluate the cluster as hardware, dataflow, and software—not a core count.",
    sources: [src("TT-Sim architecture labs", "./index.html#experiments"), src("Tensix dataflow", source.tensix)],
  },
  {
    id: 41,
    category: "Scheduling & scaling",
    question: "How do you diagnose load imbalance?",
    answer: "I compare useful work and active time per core or stage, then trace why the slowest participant differs: uneven shard size, tail tiles, divergent paths, memory-bank pressure, routing, producer starvation, consumer backpressure, or synchronization with a straggler.",
    deeper: "Average utilization hides imbalance. I inspect distributions and critical-path completion, then compare repartitioning, different grid shapes, work stealing where legal, shape specialization, or fewer cores with larger balanced tiles.",
    proof: "Maximum-to-average stage time and barrier wait shrink, traffic does not regress, and end-to-end performance improves.",
    memory: "The barrier runs at the speed of the slowest participant.",
    sources: [src("Device profiler", source.profiler), src("Synchronization guide", "./discussion-blackhole-synchronization.html")],
  },
  {
    id: 42,
    category: "Scheduling & scaling",
    question: "How do data locality and communication cost affect scheduling?",
    answer: "A schedule that maximizes arithmetic parallelism can still lose if it repeatedly moves shared operands or partial results across expensive links. I place producers, consumers, and reusable state to minimize critical bytes while preserving enough parallelism and balance.",
    deeper: "Locality choices include stationary operands, multicast, shard orientation, collective placement, and pipeline boundaries. I compare bytes and hop or link pressure, not just distance, because contention and synchronization determine effective communication cost.",
    proof: "NoC or link bytes, occupancy, stalls, collective time, locality hit, imbalance, and SLO before and after mapping.",
    memory: "Schedule arithmetic where its data already is—or prove movement is worth it.",
    sources: [src("Tensix dataflow", source.tensix), src("NoC API", source.noc)],
  },
  {
    id: 43,
    category: "Scheduling & scaling",
    question: "What synchronization problems commonly appear in NPU kernels?",
    answer: "Common failures include publishing before transfer completion, waiting on the wrong NoC or semaphore domain, unbalanced circular-buffer reserve/push/wait/pop, reusing a buffer while a consumer still owns it, missing participants, stale epochs, and barriers that serialize too much.",
    deeper: "I identify the exact dependency that must cross compiler, local RISC, NoC, cross-core readiness, buffer ownership, or compute-pipeline boundaries. A compiler fence, RISC-V fence, NoC barrier, semaphore, and circular-buffer credit are different guarantees.",
    proof: "Waypoints and focused fault injection reproduce the missing edge; deterministic stress passes after the narrowest correct primitive is installed.",
    memory: "Name the dependency domain before choosing the synchronization primitive.",
    sources: [src("Synchronization field guide", "./discussion-blackhole-synchronization.html"), src("NoC API", source.noc)],
  },
  {
    id: 44,
    category: "Scheduling & scaling",
    question: "How do pipeline scheduling and backpressure interact?",
    answer: "A pipeline runs at the rate of its slowest steady-state stage. If a consumer is slower, output buffers fill and backpressure reaches upstream compute and readers; if a producer is slower, downstream stages starve. Buffering absorbs short variation but cannot fix a persistent rate mismatch.",
    deeper: "I measure reader, compute, and writer time plus queue occupancy and waits, then change tile shape, work allocation, buffer depth, transfer overlap, or stage implementation. Excess buffering can hide the symptom while increasing latency and local-memory pressure.",
    proof: "Stage times converge, queue occupancy remains bounded, waits decrease, and throughput improves without latency or memory regression.",
    memory: "Buffers absorb bursts; balance fixes steady-state backpressure.",
    sources: [src("Circular-buffer API", source.cb), src("Device profiler", source.profiler)],
  },
  {
    id: 45,
    category: "Evidence & leadership",
    question: "How would you debug a performance regression?",
    answer: "I first reproduce it with the same model, inputs, shapes, precision, warm-up, device, and measurement boundary. Then I bisect software or configuration, compare operation and per-core traces, identify the first changed phase or counter, and distinguish compile/cache changes from steady-state execution.",
    deeper: "I keep correctness as a gate and look for layout conversions, dispatch gaps, changed tiling or grid, memory-plan growth, lost overlap, added bytes, synchronization, and fallback kernels. I revert or fix the narrow cause rather than tuning around it.",
    proof: "The responsible change predicts the profiler delta; reverting or correcting it restores clean repeated performance and correctness.",
    memory: "Freeze the boundary, bisect the change, explain the trace, restore the metric.",
    sources: [src("TTNN profiling", source.ttnnProfiler), src("Performance method", source.performance)],
  },
  {
    id: 46,
    category: "Evidence & leadership",
    question: "What can you do if you have only a simulator and no real hardware?",
    answer: "I use the simulator for functional verification, architectural sequence, API contracts, address and buffer experiments, scheduling comparisons, fault injection, and narrowing candidate designs. I pin simulator and TT-Metal revisions and compare against an independent numerical oracle.",
    deeper: "I do not claim silicon latency, bandwidth, power, thermals, contention, or system overhead from simulator wall time unless the simulator explicitly provides and validates that model. I predefine the later hardware experiment so simulation produces a shortlist rather than a performance claim.",
    proof: "Golden outputs, negative tests, reproducible configuration, resource counts, and an explicit list of measurements deferred to hardware.",
    memory: "Simulate to eliminate bad designs; use hardware to claim performance.",
    sources: [src("Official ttsim repository", source.ttsim), src("TT-Sim lab", "./index.html#experiments")],
  },
  {
    id: 47,
    category: "Evidence & leadership",
    question: "Why is real hardware still necessary after simulation?",
    answer: "Real hardware establishes sustained bandwidth, actual latency, queue and runtime overhead, contention, link behavior, power, thermal throttling, clocking, firmware interactions, and system-level variability. These effects can change both the bottleneck and the ranking of simulated designs.",
    deeper: "My handoff is a two-gate process: simulator-backed correctness and architectural evidence, then a named device, workload, counters, power method, repeated measurements, and acceptance thresholds. A mismatch is information for calibrating the model, not a reason to hide it.",
    proof: "Hardware results reproduce functional behavior and either confirm the predicted ranking or explain the model gap with measured evidence.",
    memory: "Simulation proves the contract; hardware proves the product behavior.",
    sources: [src("Official ttsim repository", source.ttsim), src("Performance method", source.performance)],
  },
  {
    id: 48,
    category: "Evidence & leadership",
    question: "How should you describe your Tenstorrent experience precisely?",
    answer: "I would say: ‘I retargeted and validated a Tenstorrent-derived compiler/runtime stack on our custom automotive NPU. My work covered model conversion and quantization, dependency-safe scheduling and resource fit, dispatch and L1/RISC debugging, and ARM-host integration.’",
    deeper: "I explicitly separate my contribution from Tenstorrent's platform authorship and separate historical professional work from current public-stack study. I can discuss public concepts and my engineering method, while proprietary source, employer measurements, and product details remain bounded.",
    proof: "Résumé-supported scope, four enabled model families, clear ownership language, and public source references for platform concepts.",
    memory: "Retargeted, integrated, debugged, and validated—did not author the platform.",
    sources: [src("Technical portfolio", source.portfolio), src("Public résumé", source.resume)],
  },
  {
    id: 49,
    category: "Evidence & leadership",
    question: "How is your recent C++/CUDA and NDT work relevant to NPU architecture?",
    answer: "The hardware differs, but the systems method transfers directly: instrument the complete acquisition path, reconcile produced and consumed work, separate compute from DMA, copies, allocation, synchronization, and backpressure, then move the smallest responsible boundary and validate on real hardware.",
    deeper: "In the NDT pipeline, control remains in C# while the high-throughput path uses C++, CUDA, reusable or zero-copy buffers, bounded producer–consumer ownership, and overlap. That demonstrates end-to-end performance engineering rather than a claim that GPU and NPU programming are identical.",
    proof: "Resume-supported real-time acquisition beyond the C# path, hardware-in-the-loop validation, and an explicit boundary around confidential rates and production details.",
    memory: "Different accelerator; same discipline: bytes, ownership, overlap, backpressure, proof.",
    sources: [src("PIE/NDT case study", `${source.portfolio}/pie-ndt`), src("Performance method", source.performance)],
  },
  {
    id: 50,
    category: "Evidence & leadership",
    question: "What would your first 30 days look like on Huawei's NPU software stack?",
    answer: "I would first map MindSpore or framework entry points into CANN graph, operator, compiler, runtime, memory, and Ascend C execution boundaries. Then I would bring up one representative operator, reproduce its correctness and warm performance, learn the official profiling flow, and trace one bottleneck from model graph to device evidence.",
    deeper: "I would meet compiler, runtime, kernel, architecture, and product owners; document SLOs and known bottlenecks; compare my Tenstorrent and CUDA mental models without assuming equivalence; and propose a small measured improvement only after the platform's existing design and constraints are understood.",
    proof: "A shared stack map, reproducible baseline, one end-to-end trace, explicit ownership and constraints, and a prioritized experiment agreed with the team.",
    memory: "Map the stack, reproduce one path, earn the evidence, then recommend.",
    sources: [src("Ascend C operator guide", source.cann), src("Ascend performance guide", source.cannPerf), src("MindSpore overview", source.mindspore)],
  },
] as const satisfies readonly QAItem[];
